available vs generated data
C2SM/ETHIOPIA pull request #29
Opened 2024-10-28 08:02 UTC by leclairm

2024-10-28 08:51 UTC, GeigerJ2 approved these changes
Thank you for the PR, @leclairm! Looks fine to me. Just added one minor comment.

In addition, I think we should still have a way to denote if a data entry lives on the local machine, irrespective if it's `available` or `generated`. It could be via `type='remote'`, even though, one then loses the `file`/`dir` specification for the type. However, as I mentioned in my comment in issue #28, this actually doesn't matter for AiiDA, and I'm not sure if we really use the information somewhere else in the code. I further assume `generated` would basically _always_ be on the remote HPC?

As this isn't addressed in this PR, I'll work on it locally (and have already been), and will open another PR.

2024-10-28 08:51 UTC, GeigerJ2 commented on tests/files/configs/test_config_large.yml
> +    - preproc_output:
Isn't this of type `generated`, as it's the output of the `preproc` task, which is part of the workflow?

2024-10-28 08:56 UTC, GeigerJ2 commented on src/wcflow/parsing/_yaml_data_models.py
> +    available: ClassVar[bool] = True
I'd steer away from using stuff that doesn't work in 3.9, though... I'm not too happy with the current requirement of needing _at least_ Python 3.12.

2024-10-28 14:18 UTC, leclairm commented on src/wcflow/parsing/_yaml_data_models.py
> +    available: ClassVar[bool] = True
I actually took a shortcut to make pydantic happy but `ClassVar` was indeed not adequate.

2024-10-28 14:18 UTC, leclairm commented on src/wcflow/parsing/_yaml_data_models.py
> +    data: ConfigDataStore
Agreed for the naming convention

2024-10-28 14:20 UTC, leclairm commented on tests/files/configs/test_config_large.yml
> +    - preproc_output:
In theory yes. In the example, for some reason it's not generated by a task. We'll improve the examples later I guess.

2024-10-28 14:21 UTC, leclairm commented
> Thank you for the PR, @leclairm! Looks fine to me. Just added one minor comment.
> 
> In addition, I think we should still have a way to denote if a data entry lives on the local machine, irrespective if it's `available` or `generated`. It could be via `type='remote'`, even though, one then loses the `file`/`dir` specification for the type. However, as I mentioned in my comment in issue #28, this actually doesn't matter for AiiDA, and I'm not sure if we really use the information somewhere else in the code. I further assume `generated` would basically _always_ be on the remote HPC?
> 
> As this isn't addressed in this PR, I'll work on it locally (and have already been), and will open another PR.

Yes, let's keep that for the separate discussion.

2024-10-28 14:24 UTC, leclairm commented on src/wcflow/parsing/_yaml_data_models.py
> +    available: ClassVar[bool] = True
> But I don't think you need the variable as you can infer the variable value from the class type.

Yes, I did that first but didn't like it then. I prefer the attribute way which reads way better when used.

2024-10-28 15:35 UTC, agoscinski requested changes
Can you also adapt the `test_config_small.yml`? Most formatting issues should be fixed automatically with `hatch fmt`.

2024-10-28 15:35 UTC, agoscinski commented on src/wcflow/parsing/_yaml_data_models.py
> +    available: bool = True
If you keep it here, one can overwrite it in the yml file
```yml
data:
  available:
    - preproc_output:
        available: False
        type: file
        src: $PWD/examples/files/data/file.ncdf
```
Probably one can somehow add this to the class without making it an option in the yml file, but I am not sure about this approach as you already can infer the same information with a `available = isinstance(ConfigAvailableData, data` check to create the `core.Data`.

2024-10-29 09:02 UTC, leclairm commented on src/wcflow/parsing/_yaml_data_models.py
> +    available: bool = True
> If you keep it here, one can overwrite it in the yml file
> 
> ```yaml
> data:
>   available:
>     - preproc_output:
>         available: false
>         type: file
>         src: $PWD/examples/files/data/file.ncdf
> ```
> 
> Probably one can somehow add this to the class without making it an option in the yml file, but I am not sure about this approach as you already can infer the same information with a `available = isinstance(ConfigAvailableData)` check to create the `core.Data`.

Would that work for you? I think it fixes everything
```python
class _DataBaseModel(_NamedBaseModel):
    """
    To create an instance of a data defined in a workflow file.
    """

    type: str
    src: str
    format: str | None = None

    @field_validator("type")
    @classmethod
    def is_file_or_dir(cls, value: str) -> str:
        """."""
        if value not in ["file", "dir"]:
            msg = "Must be one of 'file' or 'dir'."
            raise ValueError(msg)
        return value

    @property
    def available(self) -> bool:
        return isinstance(self, ConfigAvailableData)


class ConfigAvailableData(_DataBaseModel):

    pass


class ConfigGeneratedData(_DataBaseModel):

    pass
```

2024-10-29 09:39 UTC, agoscinski commented on src/wcflow/parsing/_yaml_data_models.py
> +    available: bool = True
I think this is ok.

2024-10-29 10:00 UTC, leclairm commented
> Can you also adapt the `test_config_small.yml`? Most formatting issues should be fixed automatically with `hatch fmt`.

done

2024-10-29 10:14 UTC, leclairm commented
> You can always look up the code `FBT001` online and find more explanations. Then you find such a page https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument/ I think the arguments on the page are fair. Would make it also enforce keyword argument usage by changing to
> 
> ```python
>     def __init__(
>         self,
>         name: str,
>         type: str,  # noqa: A002
>         src: str,
>         lag: list[Duration],
>         date: list[datetime],
>         arg_option: str | None,
>         *
>         available: bool,
>     ):
> ```
> 
> I actually thought at some point to enforce keyword argument usage to every input argument to increase readability. But that we can do another time.

did it for `avaialble`

2024-10-29 10:15 UTC, leclairm commented on src/wcflow/parsing/_yaml_data_models.py
> +    available: ClassVar[bool] = True
Resolved with porperty

2024-10-29 11:06 UTC, agoscinski approved these changes
Looks good! Thank for the work. Could you squash merge with a commit message like this?
```
Introduce keywords that distinguish data that is available on init and not in yml file (#29)

We introduce the keywords `available` and `generated` in the yml file that
specify if the data exists already on initialization or is generated by the
workflow. Before that we needed to refer this from how the data is used in the
workflow. We decided to let the user specify this for better error control
handling. Implements suggestion from issue #28
```

2024-10-29 11:15 UTC, merged